# Generated by Django 3.0.3 on 2020-03-13 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_professors', '0002_auto_20200312_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
